theme: jekyll-theme-minimal
title: mon-gmx
description: Simplest profile page from mon-gmx
markdown: GFM
lsi: false
safe: true
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
